---

- include: facts.yml

- include: packages_redhat.yml
  when: ansible_os_family == 'RedHat'

- include: packages_debian.yml
  when: ansible_os_family == 'Debian'

- include: configuration.yml

- include: libvirt.yml
  when: openstack_nova_compute_add_tun_acl

- include: services.yml

- meta: flush_handlers

- include: sanitycheck.yml
